name: happypets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/FotoPerfil.jpg
    - assets/MaxyCloe.jpg
    - assets/Luna.jpg
    - assets/perro1.jpg
    - assets/perro2.jpg
    - assets/perro3.jpg
    - assets/gato1.jpg
    - assets/gato2.jpg
    - assets/logo.png
    - encuesta/feedback.json
    

